### ISSUE TITLE
"profile not found" in Lambda execution

### ISSUE THREAD

**Issue by bvbg1** [aws-samples/amazon-textract-textractor#176]
I added amazon-textract-textractor as a Lambda layer as it is suggested here (using Python 3.9): 
https://aws-samples.github.io/amazon-textract-textractor/using_in_lambda.html

In the code I have: 
```
from textractor import Textractor
extractor = Textractor(profile_name="default")
```
But when running the Lambda function it errors with: 

```
[ERROR] ProfileNotFound: The config profile (default) could not be found
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 5, in <module>
    extractor = Textractor(profile_name="default")
  File "/opt/python/textractor/textractor.py", line 90, in __init__
    self.session = boto3.session.Session(profile_name=self.profile_name)
  File "/opt/python/boto3/session.py", line 90, in __init__
    self._setup_loader()
  File "/opt/python/boto3/session.py", line 131, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/opt/python/botocore/session.py", line 796, in get_component
    return self._components.get_component(name)
  File "/opt/python/botocore/session.py", line 1108, in get_component
    self._components[name] = factory()
  File "/opt/python/botocore/session.py", line 193, in <lambda>
    lambda: create_loader(self.get_config_variable('data_path')),
  File "/opt/python/botocore/session.py", line 317, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/opt/python/botocore/configprovider.py", line 426, in get_config_variable
    return provider.provide()
  File "/opt/python/botocore/configprovider.py", line 628, in provide
    value = provider.provide()
  File "/opt/python/botocore/configprovider.py", line 718, in provide
    scoped_config = self._session.get_scoped_config()
  File "/opt/python/botocore/session.py", line 416, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
```

I tried with both lambda-layers #21 and lambda-layers #20 from the link above (textractor-lambda-p39). 
How can I fix this?

**Comment by Belval** [comment]
Use `region_name='us-west-2'` (replace with the correct region) instead of `profile_name`. The latter is for profiles you'd have defined in a `~/.aws/config`/`~/.aws/credentials` file.

Also make sure that your lambda's role allows it to make calls to Textract.

**Comment by bvbg1** [comment]
Thanks!
