### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by RichardScottOZ** [aws-samples/amazon-textract-textractor#25]
Likely windows problem:-

Total Pages in Document: 77
Traceback (most recent call last):
  File "textractorsandbox.py", line 169, in <module>
    Textractor().run()
  File "textractorsandbox.py", line 148, in run
    self.processDocument(ips, i, document)
  File "textractorsandbox.py", line 113, in processDocument
    opg.run()
  File "D:\amazon-textract-textractor\src\og.py", line 111, in run
    self._outputWords(page, p)
  File "D:\amazon-textract-textractor\src\og.py", line 30, in _outputWords
    csvFieldNames, csvData)
  File "D:\amazon-textract-textractor\src\helper.py", line 122, in writeCSV
    writer.writerow(row)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\singan\lib\csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\singan\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u20b9' in position 37: character maps to <undefined>

**Comment by RichardScottOZ** [comment]
Yes, seems like it was the usual :-
add in an encoding

    def writeCSV(fileName, fieldNames, csvData):
        with open(fileName, 'w', encoding='utf-8') as csv_file:
            writer = csv.DictWriter(csv_file, fieldnames=fieldNames)
            writer.writeheader()

            for item in csvData:
                i = 0
                row = {}
                for value in item:
                    row[fieldNames[i]] = value
                    i = i + 1
                writer.writerow(row)

I could foresee say latin1 being necessary in some cases, too
