### ISSUE TITLE
bug: table_linearization_format="markdown", could cause AttributeError: 'NoneType' object has no attribute 'columns'

### ISSUE THREAD

**Issue by schadem** [aws-samples/amazon-textract-textractor#255]
```
Traceback (most recent call last):
  File "/Users/schadem/code/github/schadem/python-playground/textractor-linearizer.py", line 31, in <module>
    print(document.get_text(config=config))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schadem/.pyenv/versions/3.11.1/envs/aws-scripts/lib/python3.11/site-packages/textractor/entities/document.py", line 252, in get_text
    return self.get_text_and_words(config)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schadem/.pyenv/versions/3.11.1/envs/aws-scripts/lib/python3.11/site-packages/textractor/entities/document.py", line 257, in get_text_and_words
    text, words_lists = zip(*[p.get_text_and_words(config) for p in self.pages])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schadem/.pyenv/versions/3.11.1/envs/aws-scripts/lib/python3.11/site-packages/textractor/entities/document.py", line 257, in <listcomp>
    text, words_lists = zip(*[p.get_text_and_words(config) for p in self.pages])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schadem/.pyenv/versions/3.11.1/envs/aws-scripts/lib/python3.11/site-packages/textractor/entities/page.py", line 180, in get_text_and_words
    page_texts_and_words = [l.get_text_and_words(config) for l in sorted_layouts]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schadem/.pyenv/versions/3.11.1/envs/aws-scripts/lib/python3.11/site-packages/textractor/entities/page.py", line 180, in <listcomp>
    page_texts_and_words = [l.get_text_and_words(config) for l in sorted_layouts]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schadem/.pyenv/versions/3.11.1/envs/aws-scripts/lib/python3.11/site-packages/textractor/entities/layout.py", line 172, in get_text_and_words
    final_text, final_words = linearize_children(
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/schadem/.pyenv/versions/3.11.1/envs/aws-scripts/lib/python3.11/site-packages/textractor/utils/text_utils.py", line 130, in linearize_children
    text_element, words_element = element.get_text_and_words(config)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schadem/.pyenv/versions/3.11.1/envs/aws-scripts/lib/python3.11/site-packages/textractor/entities/table.py", line 602, in get_text_and_words
    has_column = any([isinstance(c, str) for c in df.columns])
                                                  ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'columns'
```

for this sample image

![2-column-table-figure-lists](https://github.com/aws-samples/amazon-textract-textractor/assets/45048633/bdce7f75-3176-4669-a693-47c236008d52)

and this code
```
from textractcaller import call_textract, Textract_Features
from textractor.entities.document import Document, TextLinearizationConfig
import boto3

input_file = "2-column-table-figure-lists.jpg" 
textract_client = boto3.client("textract", region_name="us-east-2")
j = call_textract(
    input_document=input_file,
    features=[
        Textract_Features.FORMS,
        Textract_Features.SIGNATURES,
        Textract_Features.LAYOUT,
        Textract_Features.TABLES,
    ],
    boto3_textract_client=textract_client,
    return_job_id=True,
)

document = Document.open(j)

config = TextLinearizationConfig(
    hide_figure_layout=True,
    title_prefix="# ",
    section_header_prefix="## ",
    list_element_prefix="*",
    table_linearization_format="markdown",
)
print(document.get_text(config=config))
```

**Comment by Belval** [comment]
This should be fixed now. When pandas is not installed export to markdown is not available. The original code did not raise an exception on the pandas import, hiding the true root cause. #261 raises the proper exception that directs the use toward installing the missing package.
