### ISSUE TITLE
_parseDocumentPagesAndBlockMap NoneType Error

### ISSUE THREAD

**Issue by Jack-Lewis1** [aws-samples/amazon-textract-textractor#4]
Running into an error with specific PDF documents. I believe this is due to _parseDocumentPagesAndBlockMap not detecting blocks. 

```python
Traceback (most recent call last):
  File "c:\\Users\\User\\amazon-textract-textractor\\textractor.py", line 164, in <module>
    Textractor().run()
  File "c:\\Users\\User\\amazon-textract-textractor\\textractor.py", line 143, in run
    self.processDocument(ips, i, document)
  File "c:\\Users\\User\\amazon-textract-textractor\\textractor.py", line 109, in processDocument
    ips["forms"], ips["tables"])
  File "c:\\Users\\User\\amazon-textract-textractor\\og.py", line 13, in __init__
    self.document = Document(self.response)
  File "c:\\Users\\User\\amazon-textract-textractor\\trp.py", line 599, in __init__
    self._parse()
  File "c:\\Users\\User\\amazon-textract-textractor\\trp.py", line 631, in _parse
    self._responseDocumentPages, self._blockMap = self._parseDocumentPagesAndBlockMap()
  File "c:\\Users\\User\\amazon-textract-textractor\\trp.py", line 614, in _parseDocumentPagesAndBlockMap
    for block in page['Blocks']:
TypeError: 'NoneType' object is not subscriptable ```

**Comment by sumitsingh2415** [comment]
Hey Jack-Lewis1,

What input are you giving for the BucketName and Documents?

I tried giving:
//bucketName = 'textracts3'
        documents = 's3://textracts3/test/ --text --forms --tables --region us-east-1 --insights --medical-insights --translate es'
        awsRegion = 'us-east-1'//

but I am getting error stating "Invalid input: Document or path to a folder or S3 bucket containing documents is required."

**Comment by Jack-Lewis1** [comment]
I have recieved a response from Amazon support for my documents that were not processing. 

>  This issue sometimes happen for particular type of PDF, I raised this issue to our service team for further investigation, I will get back as soon as possible after getting the response from the service team and if we need any farther information from your side.

**Comment by shailendrasingh** [comment]
I am also getting the same error inside `trp.py` at line number 624 with error message `AttributeError: 'NoneType' object has no attribute 'append'`  while reading Current Account Bank Statement of HDFC Bank.

**Comment by darwaishx** [comment]
Issue is addressed. It was caused if Textract job was not successful and tdp.py was returning None as response.
